hw04: DayOfYear.o main.cpp
	g++ -Wall -std=c++11 -o hw04 DayOfYear.o main.cpp

DayOfYear.o: DayOfYear.hpp DayOfYear.cpp
	g++ -Wall -std=c++11 -c DayOfYear.cpp

clean:
	rm -f core DayOfYear.o BST.o hw04
